//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCar
    {
        public int Car_Id { get; set; }
        public string Car_Name { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Price { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string Transmission { get; set; }
        public string Fuel_Type { get; set; }
        public string Features { get; set; }
        
    }
}
